Repository 10up/ElasticPress, pull requests merged in 2019-07, with the labels that each got.

#1378 Add support for nested taxonomy queries
  includes/classes/Indexable/Post/Post.php
  tests/indexables/TestPost.php
Labels: enhancement

#1347 Delete pagination from facet URL
  includes/classes/Feature/Facets/Facets.php
Labels: bug

#1355 Add filters to control MLT related posts params
  includes/classes/Feature/RelatedPosts/RelatedPosts.php
Labels: enhancement

#1344 Product attribute facets for 3.0.
  includes/classes/Feature/Facets/Facets.php
  includes/classes/Feature/Facets/Widget.php
  includes/classes/Feature/WooCommerce/WooCommerce.php
Labels: enhancement

#1358 Add/post content filtered indexing
  includes/classes/Indexable/Post/Post.php
Labels: enhancement

#1382 Documentation updates
  CHANGELOG.md
  LICENSE.md
  README.md
Labels: documentation needed

#1398 Support ES 7.0+
  elasticpress.php
  includes/classes/Elasticsearch.php
  includes/classes/Feature/Autosuggest/Autosuggest.php
  includes/classes/Indexable/Post/Post.php
  includes/classes/Indexable/Post/QueryIntegration.php
  includes/classes/Indexable/User/QueryIntegration.php
  includes/classes/Indexable/User/User.php
  includes/mappings/post/7-0.php
  includes/mappings/user/7-0.php
Labels: enhancement

#1399 Delete wpcli sync option/transient when an error occurs
  includes/classes/Command.php
Labels: bug

#1400 Ensure new sites within multisite have the correct mappings and global alias
  includes/classes/Command.php
  includes/classes/Elasticsearch.php
  includes/classes/Indexable/Post/SyncManager.php
Labels: bug

#1406 Update phrasing in Step 2 of setup process
  images/setup-screenshot.png
  includes/partials/install-page.php
Labels: documentation needed

#1409 Update readme.txt to match readme.md
  readme.txt
Labels: documentation needed
