Repository 10up/ElasticPress, pull requests merged in 2020-01, with the labels that each got.

#1616 Readd ep_retrieve_aggregations hook for backwards compat
  includes/classes/Elasticsearch.php
Labels: enhancement

#1621 Fixes for WP_User_Query 'fields' parameter
  .gitignore
  docs/development.md
  includes/classes/Indexable/User/QueryIntegration.php
  tests/php/TestUtils.php
  tests/php/indexables/TestUser.php
Labels: bug

#1634 Add ep_prepared_*_meta filters
  includes/classes/Indexable/Post/Post.php
  includes/classes/Indexable/User/User.php
Labels: enhancement

#1617 Support all taxonomies in root WP_Query
  includes/classes/Indexable/Post/Post.php
Labels: bug

#1637 CLI Index Refactor
  includes/classes/Command.php
Labels: enhancement

#1624 Moved EP indexable posts class registration into a function that runs in the plugins_loaded action
  elasticpress.php
  includes/classes/Elasticsearch.php
  tests/php/indexables/TestPost.php
Labels: bug

#1643 Cast taxonomy slug to array in case it's already an array
  includes/classes/Indexable/Post/Post.php
Labels: bug

#1640 Limit Protected Content Post Types
  includes/classes/Feature/ProtectedContent/ProtectedContent.php
  includes/classes/Indexable/Post/SyncManager.php
Labels: enhancement

#1443 Add a Terms Indexable
  README.md
  composer.json
  elasticpress.php
  includes/classes/Feature/Terms/Terms.php
  includes/classes/Indexable.php
  includes/classes/Indexable/Term/QueryIntegration.php
  includes/classes/Indexable/Term/SyncManager.php
  includes/classes/Indexable/Term/Term.php
  includes/dashboard.php
  includes/mappings/term/7-0.php
  includes/mappings/term/initial.php
  includes/mappings/term/pre-5-0.php
  tests/php/includes/functions.php
  tests/php/indexables/TestTerm.php
Labels: documentation needed, enhancement
