Repository 10up/ElasticPress, pull requests merged in 2021-08, with the labels that each got.

#2283 Restore current blog when the_post triggers outside the loop.
  bin/install-wp-tests.sh
  includes/classes/Indexable/Post/QueryIntegration.php
  tests/php/indexables/TestPost.php
Labels: high priority

#1472 Feature implementation for #1471
  includes/classes/AdminNotices.php
  includes/classes/Indexable/Post/Post.php
  includes/mappings/post/5-0.php
  includes/mappings/post/5-2.php
  includes/mappings/post/7-0.php
  includes/mappings/post/pre-5-0.php
  tests/php/TestAdminNotices.php
Labels: high priority

#2290 Fix command stats and status
  includes/classes/Command.php
Labels: high priority, bug

#2287 Synonyms Type
  includes/classes/Feature/Search/Synonyms.php
Labels: high priority

#2284 fix #2275
  includes/classes/Indexable/Post/SyncManager.php
  includes/classes/SyncManager.php
Labels: high priority

#2313 Fix: WP Acceptance tests and Page Crashed errors tolerance
  run-wpacceptance.sh
Labels: high priority

#2306 Enable @10up/eslint-config/react and fix warnings and erros
  .babelrc
  .eslintrc.js
  assets/js/autosuggest.js
  assets/js/blocks/related-posts/Edit.js
  assets/js/blocks/related-posts/block.js
  assets/js/comments.js
  assets/js/dashboard.js
  assets/js/facets.js
  assets/js/ordering/index.js
  assets/js/ordering/pointers.js
  assets/js/sites-admin.js
  assets/js/stats.js
  assets/js/synonyms/components/SynonymsEditor.js
  assets/js/synonyms/components/editors/AlternativeEditor.js
  assets/js/synonyms/components/editors/AlternativesEditor.js
  assets/js/synonyms/components/editors/SetsEditor.js
  assets/js/synonyms/components/editors/SolrEditor.js
  assets/js/synonyms/components/shared/LinkedMultiInput.js
  assets/js/synonyms/components/shared/MultiInput.js
  assets/js/synonyms/context.js
  assets/js/synonyms/index.js
  assets/js/synonyms/reducers/editorReducer.js
  assets/js/synonyms/utils.js
  assets/js/utils/helpers.js
  dist/css/autosuggest-styles.min.css
  dist/css/dashboard-styles.min.css
  dist/css/sites-admin-styles.min.css
  dist/css/synonyms-styles.min.css
  dist/js/admin-script.min.js
  dist/js/autosuggest-script.min.js
  dist/js/comments-script.min.js
  dist/js/dashboard-script.min.js
  dist/js/facets-script.min.js
  dist/js/ordering-script.min.js
  dist/js/related-posts-block-script.min.js
  dist/js/stats-script.min.js
  dist/js/synonyms-script.min.js
  package-lock.json
  package.json
Labels: enhancement, high priority

#2312 Fix indexing button on health screen
  includes/dashboard.php
  includes/partials/stats-page.php
Labels: confirmed bug

#2320 Update PHP Version info (5.4 -> 5.6)
  .github/hookdoc-tmpl/README.md
  CHANGELOG.md
  README.md
  docs/install.md
  elasticpress.php
Labels: high priority

#2288 Fix/facets order
  includes/classes/Feature/Facets/Widget.php
Labels: high priority

#2267 Utility function for checking if a request should be integrated.
  includes/classes/Elasticsearch.php
  includes/classes/Feature/Autosuggest/Autosuggest.php
  includes/classes/Feature/Documents/Documents.php
  includes/classes/Feature/ProtectedContent/ProtectedContent.php
  includes/classes/Feature/Search/Search.php
  includes/classes/Feature/Search/Weighting.php
  includes/classes/Feature/WooCommerce/WooCommerce.php
  includes/utils.php
  tests/php/indexables/TestPost.php
Labels: high priority
