Repository 10up/ElasticPress, pull requests merged in 2021-12, with the labels that each got.

#2484 Add a "request" subcommand
  includes/classes/Command.php
Labels: high priority

#2408 Account for password protected posts via protected_content feature
  includes/classes/Feature/ProtectedContent/ProtectedContent.php
  includes/classes/Indexable/Post/Post.php
  includes/mappings/post/5-2.php
  includes/mappings/post/7-0.php
  tests/php/features/TestProtectedContent.php
Labels: enhancement, high priority

#2485 Update min PHP version to 7.0
  .github/hookdoc-tmpl/README.md
  docs/install.md
  elasticpress.php
Labels: high priority

#2448 Adjust visuals sync progress
  assets/css/sync.css
  assets/js/sync.js
  dist/css/sync-styles.min.css
  dist/js/autosuggest-script.min.js
  dist/js/comments-script.min.js
  dist/js/dashboard-script.min.js
  dist/js/facets-script.min.js
  dist/js/ordering-script.min.js
  dist/js/related-posts-block-script.min.js
  dist/js/stats-script.min.js
  dist/js/sync-script.min.js
  dist/js/synonyms-script.min.js
  dist/js/weighting-script.min.js
  images/pause.svg
  images/resume.svg
  images/stop.svg
  images/sync-in-progress.png
  images/thumbsdown.svg
  images/thumbsup.svg
  images/warning.svg
  includes/classes/IndexHelper.php
  includes/partials/header.php
  includes/partials/sync-page.php
  package-lock.json
  package.json
Labels: enhancement

#2491 Feature/1932
  assets/css/dashboard.css
  assets/js/dashboard.js
  dist/css/dashboard-styles.min.asset.php
  dist/css/dashboard-styles.min.css
  dist/js/dashboard-script.min.asset.php
  dist/js/dashboard-script.min.js
  includes/classes/Feature.php
Labels: high priority

#2486 Build assets during the release
  .distignore
  .gitattributes
  .github/workflows/push-deploy.yml
  .gitignore
  CONTRIBUTING.md
  dist/css/autosuggest-styles.min.asset.php
  dist/css/autosuggest-styles.min.css
  dist/css/comments-styles.min.asset.php
  dist/css/comments-styles.min.css
  dist/css/dashboard-styles.min.asset.php
  dist/css/dashboard-styles.min.css
  dist/css/facets-admin-styles.min.asset.php
  dist/css/facets-admin-styles.min.css
  dist/css/facets-styles.min.asset.php
  dist/css/facets-styles.min.css
  dist/css/highlighting-styles.min.asset.php
  dist/css/highlighting-styles.min.css
  dist/css/instant-results-styles.min.asset.php
  dist/css/instant-results-styles.min.css
  dist/css/ordering-styles.min.asset.php
  dist/css/ordering-styles.min.css
  dist/css/related-posts-block-styles.min.asset.php
  dist/css/related-posts-block-styles.min.css
  dist/css/sites-admin-styles.min.asset.php
  dist/css/sites-admin-styles.min.css
  dist/css/sync-styles.min.asset.php
  dist/css/sync-styles.min.css
  dist/css/synonyms-styles.min.asset.php
  dist/css/synonyms-styles.min.css
  dist/js/autosuggest-script.min.asset.php
  dist/js/autosuggest-script.min.js
  dist/js/comments-script.min.asset.php
  dist/js/comments-script.min.js
  dist/js/dashboard-script.min.asset.php
  dist/js/dashboard-script.min.js
  dist/js/facets-script.min.asset.php
  dist/js/facets-script.min.js
  dist/js/instant-results-admin-script.min.asset.php
  dist/js/instant-results-admin-script.min.js
  dist/js/instant-results-script.min.asset.php
  dist/js/instant-results-script.min.js
  dist/js/notice-script.min.asset.php
  dist/js/notice-script.min.js
  dist/js/ordering-script.min.asset.php
  dist/js/ordering-script.min.js
  dist/js/related-posts-block-script.min.asset.php
  dist/js/related-posts-block-script.min.js
  dist/js/sites-admin-script.min.asset.php
  dist/js/sites-admin-script.min.js
  dist/js/stats-script.min.asset.php
  dist/js/stats-script.min.js
  dist/js/sync-script.min.asset.php
  dist/js/sync-script.min.js
  dist/js/synonyms-script.min.asset.php
  dist/js/synonyms-script.min.js
  dist/js/weighting-script.min.asset.php
  dist/js/weighting-script.min.js
  elasticpress.php
  package-lock.json
  package.json
Labels: high priority

#2500 Instant Results: Add link to the PHP proxy
  includes/classes/Feature/InstantResults/InstantResults.php
Labels: high priority

#2498 New search algorithm
  includes/classes/Feature/Search/Weighting.php
  includes/classes/Indexable/Post/Post.php
Labels: high priority

#2490 [Release] 4.0.0 Beta 1
  CHANGELOG.md
  CREDITS.md
  includes/classes/Upgrades.php
Labels: high priority

#2501 Fix AJAX URL on subsite
  assets/js/sync.js
  includes/classes/Screen/Sync.php
Labels: confirmed bug

#2517 Synonyms: ignore ep-synonym post status
  includes/classes/Feature/Search/Synonyms.php
  includes/classes/Upgrades.php
Labels: high priority

#2524 Display a notice that content will be reindexed when enabling a feature that requires it
  assets/css/dashboard.css
  assets/js/dashboard.js
  dist/css/dashboard-styles.min.css
  dist/js/dashboard-script.min.js
  includes/classes/Feature.php
Labels: high priority

#2525 Deleting a metadata without passing an object id now updates all associated posts
  includes/classes/Indexable/Post/SyncManager.php
  tests/php/indexables/TestPost.php
Labels: high priority

#2536 Fix usage of requiresReindex
  assets/js/dashboard.js
  dist/js/dashboard-script.min.js
  includes/classes/Upgrades.php
Labels: high priority

#2521 [Release] 3.6.6
  CHANGELOG.md
  CREDITS.md
  README.md
  elasticpress.php
  package-lock.json
  package.json
  readme.txt
Labels: high priority

#2535 Update GH actions versions
  .github/workflows/build-docs.yml
  .github/workflows/push-asset-readme-update.yml
  .github/workflows/push-deploy.yml
Labels: high priority
