Repository 10up/ElasticPress, pull requests merged in 2021-04, with the labels that each got.

#2162 Remove source mappings
  config/webpack.prod.js
  dist/css/autosuggest-styles.min.css
  dist/css/autosuggest-styles.min.css.map
  dist/css/dashboard-styles.min.css
  dist/css/dashboard-styles.min.css.map
  dist/css/facets-admin-styles.min.css
  dist/css/facets-admin-styles.min.css.map
  dist/css/facets-styles.min.css
  dist/css/facets-styles.min.css.map
  dist/css/highlighting-styles.min.css
  dist/css/highlighting-styles.min.css.map
  dist/css/ordering-styles.min.css
  dist/css/ordering-styles.min.css.map
  dist/css/related-posts-block-styles.min.css
  dist/css/related-posts-block-styles.min.css.map
  dist/css/sites-admin-styles.min.css
  dist/css/sites-admin-styles.min.css.map
  dist/css/synonyms-styles.min.css
  dist/css/synonyms-styles.min.css.map
  dist/js/admin-script.min.js
  dist/js/admin-script.min.js.map
  dist/js/autosuggest-script.min.js
  dist/js/autosuggest-script.min.js.map
  dist/js/dashboard-script.min.js
  dist/js/dashboard-script.min.js.map
  dist/js/facets-script.min.js
  dist/js/facets-script.min.js.map
  dist/js/ordering-script.min.js
  dist/js/ordering-script.min.js.map
  dist/js/related-posts-block-script.min.js
  dist/js/related-posts-block-script.min.js.map
  dist/js/sites-admin-script.min.js
  dist/js/sites-admin-script.min.js.map
  dist/js/stats-script.min.js
  dist/js/stats-script.min.js.map
  dist/js/synonyms-script.min.js
  dist/js/synonyms-script.min.js.map
Labels: enhancement

#2163 Autosuggest: don't enqueue scripts if EP is indexing
  includes/classes/Feature/Autosuggest/Autosuggest.php
Labels: qa

#2158 Remove references to posts_by_query property
  includes/classes/Indexable/Post/QueryIntegration.php
Labels: bug

#2157 Add support to 'NOT LIKE' operator for meta_query
  includes/classes/Indexable.php
  tests/php/indexables/TestPost.php
Labels: enhancement

#2156 Add new filter to show or not ElasticPress Indexing option
  includes/dashboard.php
Labels: enhancement

#1886 Fix/1854
  assets/css/facets.css
  dist/css/facets-styles.min.css
  dist/js/facets-script.min.js
  includes/classes/Feature/Autosuggest/Autosuggest.php
  includes/classes/Feature/Facets/Widget.php
  includes/classes/Indexable/Post/Post.php
Labels: wip

#1703 Validate that a meta_value is a recognizable date value before storing
  includes/classes/Indexable.php
  tests/php/indexables/TestPost.php
Labels: high priority

#2120 Add confirmation for destructive WP-CLI commands
  includes/classes/Command.php
  tests/wpa/BasicTest.php
  tests/wpa/DashboardSyncTest.php
  tests/wpa/GeneralTest.php
  tests/wpa/StandardTest.php
  tests/wpa/WpCliTest.php
  tests/wpa/after-test/CleanUp.php
  tests/wpa/features/AutosuggestTest.php
  tests/wpa/features/DocumentTest.php
  tests/wpa/features/ProtectedContentTest.php
  tests/wpa/features/SearchTest.php
  tests/wpa/indexables/UserTest.php
  wpacceptance.json
Labels: high priority

#2084 Add test to site health
  elasticpress.php
  includes/classes/HealthCheck.php
  includes/classes/HealthCheck/HealthCheckElasticsearch.php
  includes/health-check.php
Labels: enhancement
