Repository 10up/ElasticPress, pull requests merged in 2021-03, with the labels that each got.

#2110 Update JS dependencies + Built assets
  dist/css/autosuggest-styles.min.css
  dist/css/autosuggest-styles.min.css.map
  dist/css/dashboard-styles.min.css
  dist/css/dashboard-styles.min.css.map
  dist/css/sites-admin-styles.min.css
  dist/css/sites-admin-styles.min.css.map
  dist/css/synonyms-styles.min.css
  dist/css/synonyms-styles.min.css.map
  dist/js/admin-script.min.js
  dist/js/admin-script.min.js.map
  dist/js/autosuggest-script.min.js
  dist/js/autosuggest-script.min.js.map
  dist/js/dashboard-script.min.js
  dist/js/dashboard-script.min.js.map
  dist/js/facets-script.min.js
  dist/js/facets-script.min.js.map
  dist/js/ordering-script.min.js
  dist/js/ordering-script.min.js.map
  dist/js/related-posts-block-script.min.js
  dist/js/related-posts-block-script.min.js.map
  dist/js/sites-admin-script.min.js
  dist/js/sites-admin-script.min.js.map
  dist/js/stats-script.min.js
  dist/js/stats-script.min.js.map
  dist/js/synonyms-script.min.js
  dist/js/synonyms-script.min.js.map
  package-lock.json
  package.json
Labels: dependencies, qa

#2125 Don't activate Protected Content by default when using EP.io
  includes/classes/Feature/ProtectedContent/ProtectedContent.php
Labels: confirmed bug, qa

#2081 Add the `ep_highlight_should_add_clause` filter
  includes/classes/Feature/Search/Search.php
Labels: qa

#2045 Add missing options and transients to be removed on uninstall
  uninstall.php
Labels: confirmed bug, qa

#2075 Add new filter to customize HTTP headers in Autosuggest request
  assets/js/autosuggest.js
  dist/js/autosuggest-script.min.js
  dist/js/autosuggest-script.min.js.map
  includes/classes/Feature/Autosuggest/Autosuggest.php
Labels: enhancement

#2080 Facets: Check if $agg['buckets'] really exists
  includes/classes/Feature/Facets/Facets.php
Labels: qa

#2137 WP-CLI: Add terms to status and stats
  includes/classes/Command.php
Labels: enhancement, qa
