Repository 10up/ElasticPress, pull requests merged in 2021-02, with the labels that each got.

#2004 Support multiple Facets
  assets/js/facets.js
  dist/js/facets-script.min.js
  dist/js/facets-script.min.js.map
Labels: qa

#2069 Fix for https://github.com/10up/ElasticPress/issues/2065
  includes/classes/Indexable/Post/Post.php
Labels: bug, needs discussion

#2068 Reapply/pr 2004: Support multiple Facets
  assets/js/facets.js
  dist/js/facets-script.min.js
  dist/js/facets-script.min.js.map
Labels: bug

#2070 Add a class to the search form when autosuggestions are loading. Addresses #1610.
  assets/js/autosuggest.js
  dist/js/autosuggest-script.min.js
  dist/js/autosuggest-script.min.js.map
Labels: qa

#2090 WP-CLI commands to get and set the search algorithm version
  includes/classes/Command.php
  includes/classes/Indexable/Post/Post.php
Labels: enhancement, qa

#2094 Autosuggest: check if `epas.highlightingTag` is set before using it
  assets/js/autosuggest.js
  dist/js/autosuggest-script.min.js
  dist/js/autosuggest-script.min.js.map
Labels: qa

#2102 Add filters for easier search algorithm manipulation
  includes/classes/Feature/Search/Weighting.php
  includes/classes/Indexable/Post/Post.php
Labels: qa

#2105 Autosuggest: Helper function to delete cached query
  includes/classes/Command.php
  includes/classes/Feature/Autosuggest/Autosuggest.php
  includes/classes/Features.php
  includes/dashboard.php
Labels: confirmed bug, qa
