Repository 10up/ElasticPress, pull requests merged in 2021-06, with the labels that each got.

#2222 Fix post_mime_type argument
  includes/classes/Indexable/Post/Post.php
  tests/php/indexables/TestPost.php
Labels: high priority

#2196 (chore): make post SyncManager extendable
  includes/classes/Indexable.php
  includes/classes/Indexable/Post/SyncManager.php
  includes/mappings/post/5-0.php
  includes/mappings/post/5-2.php
  includes/mappings/post/7-0.php
  includes/mappings/post/pre-5-0.php
Labels: high priority, qa

#2219 Fix: autosuggest breaks search blocks
  assets/js/autosuggest.js
  dist/js/autosuggest-script.min.js
Labels: high priority, qa

#2226 Fix WP_Query_User when it tries to sort the results
  includes/classes/Indexable/User/User.php
  includes/mappings/user/7-0.php
  includes/mappings/user/initial.php
  includes/mappings/user/pre-5-0.php
  tests/php/indexables/TestUser.php
Labels: confirmed bug, high priority

#2171 Implement ID ranges instead of relying on OFFSET when doing pagination.
  docs/wp-cli.md
  includes/classes/Command.php
  includes/classes/Indexable/Post/Post.php
  includes/dashboard.php
  tests/php/indexables/TestPost.php
Labels: high priority, qa

#1689 Feature/post type enhancements
  assets/js/autosuggest.js
  dist/js/admin-script.min.js
  dist/js/autosuggest-script.min.js
  dist/js/dashboard-script.min.js
  dist/js/facets-script.min.js
  dist/js/ordering-script.min.js
  dist/js/related-posts-block-script.min.js
  dist/js/stats-script.min.js
  dist/js/synonyms-script.min.js
  includes/classes/Feature/Facets/Facets.php
  tests/php/features/TestFacet.php
Labels: high priority

#1531 Add a Comments Indexable
  docs/indexables.md
  elasticpress.php
  includes/classes/Feature/Comments/Comments.php
  includes/classes/Feature/ProtectedContent/ProtectedContent.php
  includes/classes/Indexable/Comment/Comment.php
  includes/classes/Indexable/Comment/QueryIntegration.php
  includes/classes/Indexable/Comment/SyncManager.php
  includes/classes/Indexable/Post/SyncManager.php
  includes/dashboard.php
  includes/mappings/comment/7-0.php
  includes/mappings/comment/initial.php
  includes/mappings/comment/pre-5-0.php
  tests/php/features/TestComments.php
  tests/php/includes/functions.php
  tests/php/indexables/TestComment.php
Labels: enhancement, high priority, needs documentation, needs tests

#2243 Output of output_index_errors()
  includes/classes/Command.php
Labels: high priority

#2238 Widget to search only on comments
  assets/css/comments.css
  assets/js/comments.js
  config/webpack.settings.js
  dist/css/comments-styles.min.css
  dist/js/comments-script.min.js
  includes/classes/Feature/Comments/Comments.php
  includes/classes/Feature/Comments/Widget.php
Labels: high priority

#2246 Bump browserslist and jsdoc versions
  package-lock.json
  package.json
Labels: high priority
