Repository 10up/ElasticPress, pull requests merged in 2022-02, with the labels that each got.

#2564 Show WP-CLI progress on sync page
  assets/js/sync.js
  includes/classes/Screen/Sync.php
Labels: bug

#2446 test/2375: Setup Cypress for E2E testing
  .github/workflows/cypress-tests.yml
  .github/workflows/test.yml
  .wp-env.json
  assets/js/stats.js
  bin/.gitignore
  bin/es-docker/Dockerfile
  bin/es-docker/docker-compose.yml
  bin/es-docker/elasticsearch.yml
  bin/setup-cypress-env.sh
  composer.json
  composer.lock
  dist/js/stats-script.min.js
  package-lock.json
  package.json
  run-wpacceptance.sh
  tests/cypress/.eslintrc.json
  tests/cypress/.gitignore
  tests/cypress/README.md
  tests/cypress/config.json
  tests/cypress/fixtures/example.json
  tests/cypress/fixtures/pdf-file.pdf
  tests/cypress/fixtures/pptx-file.pptx
  tests/cypress/integration/dashboard-sync.spec.js
  tests/cypress/integration/features/autosuggest.spec.js
  tests/cypress/integration/features/documents.spec.js
  tests/cypress/integration/features/protected-content.spec.js
  tests/cypress/integration/features/related-posts.spec.js
  tests/cypress/integration/features/search/search.spec.js
  tests/cypress/integration/features/search/weighting.spec.js
  tests/cypress/integration/features/woocommerce.spec.js
  tests/cypress/integration/general.spec.js
  tests/cypress/integration/indexables/user.spec.js
  tests/cypress/integration/wp-basic.spec.js
  tests/cypress/integration/wp-cli.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/global-hooks.js
  tests/cypress/support/index.js
  tests/cypress/wordpress-files/test-docs/content-example.xml
  tests/cypress/wordpress-files/test-mu-plugins/unique-index-name.php
  tests/cypress/wordpress-files/test-plugins/fake-new-activation.php
  tests/cypress/wordpress-files/test-plugins/unsupported-elasticsearch-version.php
  tests/wpa/BasicTest.php
  tests/wpa/DashboardSyncTest.php
  tests/wpa/GeneralTest.php
  tests/wpa/HighlightingTest.php
  tests/wpa/StandardTest.php
  tests/wpa/WpCliTest.php
  tests/wpa/after-test/CleanUp.php
  tests/wpa/bootstrap.php
  tests/wpa/features/AutosuggestTest.php
  tests/wpa/features/DocumentTest.php
  tests/wpa/features/ProtectedContentTest.php
  tests/wpa/features/RelatedPostsTest.php
  tests/wpa/features/SearchTest.php
  tests/wpa/features/WooCommerceTest.php
  tests/wpa/inc/TestBase.php
  tests/wpa/indexables/UserTest.php
  tests/wpa/test-mu-plugins/unique-index-name.php
  wpacceptance.json
Labels: high priority

#2604 Add history and shareable URLs support to Instant Results
  assets/js/blocks/related-posts/Edit.js
  assets/js/instant-results/components/common/checkbox-list.js
  assets/js/instant-results/components/facets/facet.js
  assets/js/instant-results/components/facets/post-type-facet.js
  assets/js/instant-results/components/facets/price-range-facet.js
  assets/js/instant-results/components/facets/search-term-facet.js
  assets/js/instant-results/components/facets/taxonomy-terms-facet.js
  assets/js/instant-results/components/layout.js
  assets/js/instant-results/components/tools/clear-constraints.js
  assets/js/instant-results/components/tools/sort.js
  assets/js/instant-results/config.js
  assets/js/instant-results/functions.js
  assets/js/instant-results/index.js
  assets/js/instant-results/reducer.js
  assets/js/instant-results/utilities.js
  includes/classes/Feature/InstantResults/InstantResults.php
Labels: enhancement
